### ISSUE TITLE
Fresh install with actix-web fails at compile on ring-asm

### ISSUE THREAD

**Issue by devton** [lfairy/maud#144]
Hello,

I'm facing this error when seting up a new project using newest actix-web.

specs:

**Rust:** 1.27.2

**Cargo.toml:**
```toml
[package]
name = "memeexample"
version = "0.1.0"
authors = []

[dependencies]
#cookie = "0.11"
actix-web = "0.7.3"
#maud = "0.18.1"
maud = { version = "0.18.1", features = ["actix-web"] }
```
error when cargo install
```
warning: To build the current package use `cargo build`, to install the current package run `cargo install --path .`
  Installing rchainexplorer v0.1.0 (file:///home/meme/code/memeexample)
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `rchainexplorer v0.1.0 (file:///home/meme/code/memeexample)`, intermediate artifacts can be found at `/home/meme/code/memeexample/target`

Caused by:
  multiple packages link to native library `ring-asm`, but a native library can be linked only once

package `ring v0.13.2`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `rchainexplorer v0.1.0 (file:///home/meme/code/memeexample)`
links to native library `ring-asm`

package `ring v0.12.1`
    ... which is depended on by `cookie v0.10.1`
    ... which is depended on by `actix-web v0.6.15`
    ... which is depended on by `maud v0.18.1`
    ... which is depended on by `rchainexplorer v0.1.0 (file:///home/meme/code/memeexample)`
also links to native library `ring-asm`
```
