### ISSUE TITLE
Iron 0.5 support

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#70]
I've made the changes locally -- just need to test and publish to crates.io.

**Comment by lfairy** [comment]
This has been fixed in master, but I want to wait for iron/staticfile#91 to land before cutting a new release.

**Comment by lfairy** [comment]
staticfile has been updated, but the changes have not yet been released. If you really want to use Iron 0.5, then you can make it work using git dependencies:

```toml
[dependencies]
# ...
iron = "0.5.1"
maud = { git = "https://github.com/lfairy/maud.git", features = ["iron"] }
maud_macros = { git = "https://github.com/lfairy/maud.git" }
staticfile = { git = "https://github.com/iron/staticfile.git", features = ["cache"] }
# ...
```
